export type StandardTextId =
  | 'STD_COVER_BUYER_DUTY_NOTICE'
  | 'STD_COVER_SELLER_NOTICE'
  | 'STD_ASSIGNMENT_SELLER_NOTICE'
  | 'STD_ASSIGNMENT_BUYER_NOTICE'
  | 'STD_DISCLOSURES_UNVERIFIED_NOTICE'
  | 'STD_VISUAL_INSPECTION_PREFACE'
  | 'STD_VISUAL_INSPECTION_CONDITIONS'
  | 'STD_VISUAL_INSPECTION_ORAL'
  | 'STD_BUILDING_DATA_TEMPLATE'
  | 'STD_RISK_GENERAL_NOTICE'
  | 'STD_FTU_GENERAL_NOTICE'
  | 'APPENDIX_1_VILLKOR_SELLER_SBR'
  | 'APPENDIX_1_VILLKOR_BUYER_SBR'
  | 'APPENDIX_2_LITEN_BYGGORDBOK_SBR'
  | 'APPENDIX_3_LIFESPAN_TABLE_SBR'

const STANDARD_TEXT_IDS: StandardTextId[] = [
  'STD_COVER_BUYER_DUTY_NOTICE',
  'STD_COVER_SELLER_NOTICE',
  'STD_ASSIGNMENT_SELLER_NOTICE',
  'STD_ASSIGNMENT_BUYER_NOTICE',
  'STD_DISCLOSURES_UNVERIFIED_NOTICE',
  'STD_VISUAL_INSPECTION_PREFACE',
  'STD_VISUAL_INSPECTION_CONDITIONS',
  'STD_VISUAL_INSPECTION_ORAL',
  'STD_BUILDING_DATA_TEMPLATE',
  'STD_RISK_GENERAL_NOTICE',
  'STD_FTU_GENERAL_NOTICE',
  'APPENDIX_1_VILLKOR_SELLER_SBR',
  'APPENDIX_1_VILLKOR_BUYER_SBR',
  'APPENDIX_2_LITEN_BYGGORDBOK_SBR',
  'APPENDIX_3_LIFESPAN_TABLE_SBR',
]

export const STANDARD_TEXT_PATHS: Record<StandardTextId, string> = {
  STD_COVER_BUYER_DUTY_NOTICE: 'src/content/standardtexts/STD_COVER_BUYER_DUTY_NOTICE.txt',
  STD_COVER_SELLER_NOTICE: 'src/content/standardtexts/STD_COVER_SELLER_NOTICE.txt',
  STD_ASSIGNMENT_SELLER_NOTICE:
    'src/content/standardtexts/STD_ASSIGNMENT_SELLER_NOTICE.txt',
  STD_ASSIGNMENT_BUYER_NOTICE:
    'src/content/standardtexts/STD_ASSIGNMENT_BUYER_NOTICE.txt',
  STD_DISCLOSURES_UNVERIFIED_NOTICE:
    'src/content/standardtexts/STD_DISCLOSURES_UNVERIFIED_NOTICE.txt',
  STD_VISUAL_INSPECTION_PREFACE: 'src/content/standardtexts/STD_VISUAL_INSPECTION_PREFACE.txt',
  STD_VISUAL_INSPECTION_CONDITIONS:
    'src/content/standardtexts/STD_VISUAL_INSPECTION_CONDITIONS.txt',
  STD_VISUAL_INSPECTION_ORAL:
    'src/content/standardtexts/STD_VISUAL_INSPECTION_ORAL.txt',
  STD_BUILDING_DATA_TEMPLATE: 'src/content/standardtexts/STD_BUILDING_DATA_TEMPLATE.txt',
  STD_RISK_GENERAL_NOTICE: 'src/content/standardtexts/STD_RISK_GENERAL_NOTICE.txt',
  STD_FTU_GENERAL_NOTICE: 'src/content/standardtexts/STD_FTU_GENERAL_NOTICE.txt',
  APPENDIX_1_VILLKOR_SELLER_SBR:
    'src/content/standardtexts/APPENDIX_1_VILLKOR_SELLER_SBR.txt',
  APPENDIX_1_VILLKOR_BUYER_SBR:
    'src/content/standardtexts/APPENDIX_1_VILLKOR_BUYER_SBR.txt',
  APPENDIX_2_LITEN_BYGGORDBOK_SBR:
    'src/content/standardtexts/APPENDIX_2_LITEN_BYGGORDBOK_SBR.txt',
  APPENDIX_3_LIFESPAN_TABLE_SBR:
    'src/content/standardtexts/APPENDIX_3_LIFESPAN_TABLE_SBR.txt',
}

export function getStandardTextPath(id: StandardTextId): string {
  return STANDARD_TEXT_PATHS[id]
}

export function listStandardTextIds(): StandardTextId[] {
  return [...STANDARD_TEXT_IDS]
}
