export type StandardTextId =
  | 'STD_COVER_BUYER_DUTY_NOTICE'
  | 'STD_COVER_SELLER_NOTICE'
  | 'STD_ASSIGNMENT_SELLER_NOTICE'
  | 'STD_ASSIGNMENT_BUYER_NOTICE'
  | 'STD_ASSIGNMENT_APARTMENT_NOTICE'
  | 'STD_ASSIGNMENT_TEMPLATE_SELLER_2026'
  | 'STD_ASSIGNMENT_TEMPLATE_BUYER_2026'
  | 'STD_ASSIGNMENT_TEMPLATE_APARTMENT_2026'
  | 'STD_ASSIGNMENT_TEMPLATE_TU_2026'
  | 'STD_DISCLOSURES_UNVERIFIED_NOTICE'
  | 'STD_VISUAL_INSPECTION_PREFACE'
  | 'STD_VISUAL_INSPECTION_CONDITIONS'
  | 'STD_VISUAL_INSPECTION_ORAL'
  | 'STD_BUILDING_DATA_TEMPLATE'
  | 'STD_RISK_GENERAL_NOTICE'
  | 'STD_FTU_GENERAL_NOTICE'
  | 'APPENDIX_1_VILLKOR_SELLER_SBR'
  | 'APPENDIX_1_VILLKOR_BUYER_SBR'
  | 'APPENDIX_1_VILLKOR_APARTMENT_SBR'
  | 'APPENDIX_2_LITEN_BYGGORDBOK_SBR'
  | 'APPENDIX_3_LIFESPAN_TABLE_SBR'
  | 'EB_REPORT_SCOPE'
  | 'EB_REPORT_INSPECTORS'
  | 'EB_REPORT_SUMMONS_MISSING'
  | 'EB_REPORT_CONFLICT_OF_INTEREST'
  | 'EB_REPORT_PREVIOUS_INSPECTIONS_TESTS'
  | 'EB_REPORT_TESTING_DOCUMENTATION'
  | 'EB_REPORT_CONTRACT_DOCUMENTS_MISSING'
  | 'EB_REPORT_NOT_ACCESSIBLE_NONE'
  | 'EB_REPORT_DOCUMENTATION_ONLY'
  | 'EB_REPORT_APPENDICES'
  | 'EB_REPORT_DEFECTS_APPENDICES_EMPTY'
  | 'EB_REPORT_MARKER_LEGEND_MISSING'
  | 'EB_REPORT_SPECIAL_INVESTIGATION'
  | 'EB_REPORT_DEDUCTION'
  | 'EB_REPORT_NOTES_EMPTY'
  | 'EB_REPORT_APPROVAL_DECISION'
  | 'EB_REPORT_CONTINUED_FINAL_INSPECTION'
  | 'EB_REPORT_WARRANTY_END'
  | 'EB_REPORT_RECLAMATION_NOTICE'
  | 'EB_REPORT_REMEDY_DEADLINE'
  | 'EB_REPORT_REMEDY_COST'
  | 'EB_REPORT_AFTER_INSPECTION'
  | 'EB_REPORT_OTHER_NOTES'
  | 'EB_REPORT_DISTRIBUTION_LIST_MISSING'
  | 'EB_REPORT_SIGNATURE_CERTIFICATE'
  | 'EB_REPORT_NOTE_LEGEND'

const STANDARD_TEXT_IDS: StandardTextId[] = [
  'STD_COVER_BUYER_DUTY_NOTICE',
  'STD_COVER_SELLER_NOTICE',
  'STD_ASSIGNMENT_SELLER_NOTICE',
  'STD_ASSIGNMENT_BUYER_NOTICE',
  'STD_ASSIGNMENT_APARTMENT_NOTICE',
  'STD_ASSIGNMENT_TEMPLATE_SELLER_2026',
  'STD_ASSIGNMENT_TEMPLATE_BUYER_2026',
  'STD_ASSIGNMENT_TEMPLATE_APARTMENT_2026',
  'STD_ASSIGNMENT_TEMPLATE_TU_2026',
  'STD_DISCLOSURES_UNVERIFIED_NOTICE',
  'STD_VISUAL_INSPECTION_PREFACE',
  'STD_VISUAL_INSPECTION_CONDITIONS',
  'STD_VISUAL_INSPECTION_ORAL',
  'STD_BUILDING_DATA_TEMPLATE',
  'STD_RISK_GENERAL_NOTICE',
  'STD_FTU_GENERAL_NOTICE',
  'APPENDIX_1_VILLKOR_SELLER_SBR',
  'APPENDIX_1_VILLKOR_BUYER_SBR',
  'APPENDIX_1_VILLKOR_APARTMENT_SBR',
  'APPENDIX_2_LITEN_BYGGORDBOK_SBR',
  'APPENDIX_3_LIFESPAN_TABLE_SBR',
  'EB_REPORT_SCOPE',
  'EB_REPORT_INSPECTORS',
  'EB_REPORT_SUMMONS_MISSING',
  'EB_REPORT_CONFLICT_OF_INTEREST',
  'EB_REPORT_PREVIOUS_INSPECTIONS_TESTS',
  'EB_REPORT_TESTING_DOCUMENTATION',
  'EB_REPORT_CONTRACT_DOCUMENTS_MISSING',
  'EB_REPORT_NOT_ACCESSIBLE_NONE',
  'EB_REPORT_DOCUMENTATION_ONLY',
  'EB_REPORT_APPENDICES',
  'EB_REPORT_DEFECTS_APPENDICES_EMPTY',
  'EB_REPORT_MARKER_LEGEND_MISSING',
  'EB_REPORT_SPECIAL_INVESTIGATION',
  'EB_REPORT_DEDUCTION',
  'EB_REPORT_NOTES_EMPTY',
  'EB_REPORT_APPROVAL_DECISION',
  'EB_REPORT_CONTINUED_FINAL_INSPECTION',
  'EB_REPORT_WARRANTY_END',
  'EB_REPORT_RECLAMATION_NOTICE',
  'EB_REPORT_REMEDY_DEADLINE',
  'EB_REPORT_REMEDY_COST',
  'EB_REPORT_AFTER_INSPECTION',
  'EB_REPORT_OTHER_NOTES',
  'EB_REPORT_DISTRIBUTION_LIST_MISSING',
  'EB_REPORT_SIGNATURE_CERTIFICATE',
  'EB_REPORT_NOTE_LEGEND',
]

export const STANDARD_TEXT_PATHS: Record<StandardTextId, string> = {
  STD_COVER_BUYER_DUTY_NOTICE: 'src/content/standardtexts/STD_COVER_BUYER_DUTY_NOTICE.txt',
  STD_COVER_SELLER_NOTICE: 'src/content/standardtexts/STD_COVER_SELLER_NOTICE.txt',
  STD_ASSIGNMENT_SELLER_NOTICE:
    'src/content/standardtexts/STD_ASSIGNMENT_SELLER_NOTICE.txt',
  STD_ASSIGNMENT_BUYER_NOTICE:
    'src/content/standardtexts/STD_ASSIGNMENT_BUYER_NOTICE.txt',
  STD_ASSIGNMENT_APARTMENT_NOTICE:
    'src/content/standardtexts/STD_ASSIGNMENT_APARTMENT_NOTICE.txt',
  STD_ASSIGNMENT_TEMPLATE_SELLER_2026:
    'src/content/standardtexts/STD_ASSIGNMENT_TEMPLATE_SELLER_2026.txt',
  STD_ASSIGNMENT_TEMPLATE_BUYER_2026:
    'src/content/standardtexts/STD_ASSIGNMENT_TEMPLATE_BUYER_2026.txt',
  STD_ASSIGNMENT_TEMPLATE_APARTMENT_2026:
    'src/content/standardtexts/STD_ASSIGNMENT_TEMPLATE_APARTMENT_2026.txt',
  STD_ASSIGNMENT_TEMPLATE_TU_2026:
    'src/content/standardtexts/STD_ASSIGNMENT_TEMPLATE_TU_2026.txt',
  STD_DISCLOSURES_UNVERIFIED_NOTICE:
    'src/content/standardtexts/STD_DISCLOSURES_UNVERIFIED_NOTICE.txt',
  STD_VISUAL_INSPECTION_PREFACE: 'src/content/standardtexts/STD_VISUAL_INSPECTION_PREFACE.txt',
  STD_VISUAL_INSPECTION_CONDITIONS:
    'src/content/standardtexts/STD_VISUAL_INSPECTION_CONDITIONS.txt',
  STD_VISUAL_INSPECTION_ORAL:
    'src/content/standardtexts/STD_VISUAL_INSPECTION_ORAL.txt',
  STD_BUILDING_DATA_TEMPLATE: 'src/content/standardtexts/STD_BUILDING_DATA_TEMPLATE.txt',
  STD_RISK_GENERAL_NOTICE: 'src/content/standardtexts/STD_RISK_GENERAL_NOTICE.txt',
  STD_FTU_GENERAL_NOTICE: 'src/content/standardtexts/STD_FTU_GENERAL_NOTICE.txt',
  APPENDIX_1_VILLKOR_SELLER_SBR:
    'src/content/standardtexts/APPENDIX_1_VILLKOR_SELLER_SBR.txt',
  APPENDIX_1_VILLKOR_BUYER_SBR:
    'src/content/standardtexts/APPENDIX_1_VILLKOR_BUYER_SBR.txt',
  APPENDIX_1_VILLKOR_APARTMENT_SBR:
    'src/content/standardtexts/APPENDIX_1_VILLKOR_APARTMENT_SBR.txt',
  APPENDIX_2_LITEN_BYGGORDBOK_SBR:
    'src/content/standardtexts/APPENDIX_2_LITEN_BYGGORDBOK_SBR.txt',
  APPENDIX_3_LIFESPAN_TABLE_SBR:
    'src/content/standardtexts/APPENDIX_3_LIFESPAN_TABLE_SBR.txt',
  EB_REPORT_SCOPE: 'src/content/standardtexts/eb/EB_REPORT_SCOPE.txt',
  EB_REPORT_INSPECTORS: 'src/content/standardtexts/eb/EB_REPORT_INSPECTORS.txt',
  EB_REPORT_SUMMONS_MISSING:
    'src/content/standardtexts/eb/EB_REPORT_SUMMONS_MISSING.txt',
  EB_REPORT_CONFLICT_OF_INTEREST:
    'src/content/standardtexts/eb/EB_REPORT_CONFLICT_OF_INTEREST.txt',
  EB_REPORT_PREVIOUS_INSPECTIONS_TESTS:
    'src/content/standardtexts/eb/EB_REPORT_PREVIOUS_INSPECTIONS_TESTS.txt',
  EB_REPORT_TESTING_DOCUMENTATION:
    'src/content/standardtexts/eb/EB_REPORT_TESTING_DOCUMENTATION.txt',
  EB_REPORT_CONTRACT_DOCUMENTS_MISSING:
    'src/content/standardtexts/eb/EB_REPORT_CONTRACT_DOCUMENTS_MISSING.txt',
  EB_REPORT_NOT_ACCESSIBLE_NONE:
    'src/content/standardtexts/eb/EB_REPORT_NOT_ACCESSIBLE_NONE.txt',
  EB_REPORT_DOCUMENTATION_ONLY:
    'src/content/standardtexts/eb/EB_REPORT_DOCUMENTATION_ONLY.txt',
  EB_REPORT_APPENDICES: 'src/content/standardtexts/eb/EB_REPORT_APPENDICES.txt',
  EB_REPORT_DEFECTS_APPENDICES_EMPTY:
    'src/content/standardtexts/eb/EB_REPORT_DEFECTS_APPENDICES_EMPTY.txt',
  EB_REPORT_MARKER_LEGEND_MISSING:
    'src/content/standardtexts/eb/EB_REPORT_MARKER_LEGEND_MISSING.txt',
  EB_REPORT_SPECIAL_INVESTIGATION:
    'src/content/standardtexts/eb/EB_REPORT_SPECIAL_INVESTIGATION.txt',
  EB_REPORT_DEDUCTION: 'src/content/standardtexts/eb/EB_REPORT_DEDUCTION.txt',
  EB_REPORT_NOTES_EMPTY: 'src/content/standardtexts/eb/EB_REPORT_NOTES_EMPTY.txt',
  EB_REPORT_APPROVAL_DECISION:
    'src/content/standardtexts/eb/EB_REPORT_APPROVAL_DECISION.txt',
  EB_REPORT_CONTINUED_FINAL_INSPECTION:
    'src/content/standardtexts/eb/EB_REPORT_CONTINUED_FINAL_INSPECTION.txt',
  EB_REPORT_WARRANTY_END: 'src/content/standardtexts/eb/EB_REPORT_WARRANTY_END.txt',
  EB_REPORT_RECLAMATION_NOTICE:
    'src/content/standardtexts/eb/EB_REPORT_RECLAMATION_NOTICE.txt',
  EB_REPORT_REMEDY_DEADLINE:
    'src/content/standardtexts/eb/EB_REPORT_REMEDY_DEADLINE.txt',
  EB_REPORT_REMEDY_COST: 'src/content/standardtexts/eb/EB_REPORT_REMEDY_COST.txt',
  EB_REPORT_AFTER_INSPECTION: 'src/content/standardtexts/eb/EB_REPORT_AFTER_INSPECTION.txt',
  EB_REPORT_OTHER_NOTES: 'src/content/standardtexts/eb/EB_REPORT_OTHER_NOTES.txt',
  EB_REPORT_DISTRIBUTION_LIST_MISSING:
    'src/content/standardtexts/eb/EB_REPORT_DISTRIBUTION_LIST_MISSING.txt',
  EB_REPORT_SIGNATURE_CERTIFICATE:
    'src/content/standardtexts/eb/EB_REPORT_SIGNATURE_CERTIFICATE.txt',
  EB_REPORT_NOTE_LEGEND: 'src/content/standardtexts/eb/EB_REPORT_NOTE_LEGEND.txt',
}

export function getStandardTextPath(id: StandardTextId): string {
  return STANDARD_TEXT_PATHS[id]
}

export function listStandardTextIds(): StandardTextId[] {
  return [...STANDARD_TEXT_IDS]
}
