export type StandardTextId =
  | 'STD_COVER_BUYER_DUTY_NOTICE'
  | 'STD_COMPANY_CONTACT_BLOCK'
  | 'STD_TOC_BLOCK'
  | 'STD_ASSIGNMENT_OBJECT_TEMPLATE'
  | 'STD_ASSIGNMENT_MANDATE_TEXT'
  | 'STD_DISCLOSURES_UNVERIFIED_NOTICE'
  | 'STD_VISUAL_INSPECTION_PREFACE'
  | 'STD_BUILDING_DATA_TEMPLATE'
  | 'STD_NOTES_SECTION_SKELETON'
  | 'STD_RISK_GENERAL_NOTICE'
  | 'STD_FTU_GENERAL_NOTICE'
  | 'STD_SIGNATURE_TEMPLATE'
  | 'APPENDIX_1_VILLKOR_SELLER_SBR_2024'
  | 'APPENDIX_2_LITEN_BYGGORDBOK_SBR_2024'
  | 'APPENDIX_3_LIFESPAN_TABLE_SBR_2024'

const STANDARD_TEXT_IDS: StandardTextId[] = [
  'STD_COVER_BUYER_DUTY_NOTICE',
  'STD_COMPANY_CONTACT_BLOCK',
  'STD_TOC_BLOCK',
  'STD_ASSIGNMENT_OBJECT_TEMPLATE',
  'STD_ASSIGNMENT_MANDATE_TEXT',
  'STD_DISCLOSURES_UNVERIFIED_NOTICE',
  'STD_VISUAL_INSPECTION_PREFACE',
  'STD_BUILDING_DATA_TEMPLATE',
  'STD_NOTES_SECTION_SKELETON',
  'STD_RISK_GENERAL_NOTICE',
  'STD_FTU_GENERAL_NOTICE',
  'STD_SIGNATURE_TEMPLATE',
  'APPENDIX_1_VILLKOR_SELLER_SBR_2024',
  'APPENDIX_2_LITEN_BYGGORDBOK_SBR_2024',
  'APPENDIX_3_LIFESPAN_TABLE_SBR_2024',
]

export const STANDARD_TEXT_PATHS: Record<StandardTextId, string> = {
  STD_COVER_BUYER_DUTY_NOTICE: 'src/content/standardtexts/STD_COVER_BUYER_DUTY_NOTICE.txt',
  STD_COMPANY_CONTACT_BLOCK: 'src/content/standardtexts/STD_COMPANY_CONTACT_BLOCK.txt',
  STD_TOC_BLOCK: 'src/content/standardtexts/STD_TOC_BLOCK.txt',
  STD_ASSIGNMENT_OBJECT_TEMPLATE: 'src/content/standardtexts/STD_ASSIGNMENT_OBJECT_TEMPLATE.txt',
  STD_ASSIGNMENT_MANDATE_TEXT: 'src/content/standardtexts/STD_ASSIGNMENT_MANDATE_TEXT.txt',
  STD_DISCLOSURES_UNVERIFIED_NOTICE:
    'src/content/standardtexts/STD_DISCLOSURES_UNVERIFIED_NOTICE.txt',
  STD_VISUAL_INSPECTION_PREFACE: 'src/content/standardtexts/STD_VISUAL_INSPECTION_PREFACE.txt',
  STD_BUILDING_DATA_TEMPLATE: 'src/content/standardtexts/STD_BUILDING_DATA_TEMPLATE.txt',
  STD_NOTES_SECTION_SKELETON: 'src/content/standardtexts/STD_NOTES_SECTION_SKELETON.txt',
  STD_RISK_GENERAL_NOTICE: 'src/content/standardtexts/STD_RISK_GENERAL_NOTICE.txt',
  STD_FTU_GENERAL_NOTICE: 'src/content/standardtexts/STD_FTU_GENERAL_NOTICE.txt',
  STD_SIGNATURE_TEMPLATE: 'src/content/standardtexts/STD_SIGNATURE_TEMPLATE.txt',
  APPENDIX_1_VILLKOR_SELLER_SBR_2024:
    'src/content/standardtexts/APPENDIX_1_VILLKOR_SELLER_SBR_2024.txt',
  APPENDIX_2_LITEN_BYGGORDBOK_SBR_2024:
    'src/content/standardtexts/APPENDIX_2_LITEN_BYGGORDBOK_SBR_2024.txt',
  APPENDIX_3_LIFESPAN_TABLE_SBR_2024:
    'src/content/standardtexts/APPENDIX_3_LIFESPAN_TABLE_SBR_2024.txt',
}

export function getStandardTextPath(id: StandardTextId): string {
  return STANDARD_TEXT_PATHS[id]
}

export function listStandardTextIds(): StandardTextId[] {
  return [...STANDARD_TEXT_IDS]
}
