"""Verify synthetic confirmation PDFs generated by preview-eb-follow-up-confirmation.mjs."""
import json
import re
from pathlib import Path
import pdfplumber
from pypdf import PdfReader


def normalized(value):
    value = re.sub('[\u2011\u2013\u2014]', '-', value)
    return re.sub(r'\s+', '', value)


cases = json.loads(Path('tmp/pdfs/eb-follow-up-confirmation/cases.json').read_text(encoding='utf-8'))
for case in cases:
    reader = PdfReader(case['pdf'])
    data = case['data']
    acceptance = data['buyer']['acceptanceSnapshot']
    pages = [page.extract_text() for page in reader.pages]
    # Remove only our repeated furniture before checking multi-page agreements.
    body = normalized('\n'.join(re.sub(r'(?m)^(HUSHUB.*|Beställning .*\|.*)$', '', page) for page in pages))
    for part in acceptance['termsText'].split('\n\n'):
        assert normalized(part) in body, 'A frozen terms paragraph is missing or changed'
    for key, value in acceptance['consentTexts'].items():
        if acceptance['consents'][key]:
            assert normalized(value) in body, f'Missing consent: {key}'
    for value in [data['buyer']['name'], data['buyer']['invoiceName'], data['buyer']['invoiceAddress'],
                  data['project']['reportNumber'], data['project']['title'], data['seller']['name'], acceptance['termsHash']]:
        assert normalized(value) in body, f'Missing purchase fact: {value}'
    for amount in ['599,00 kr', '479,20 kr', '119,80 kr']:
        assert normalized(amount) in body, 'Missing price/VAT'
    if data['buyer']['customerType'] == 'consumer':
        assert acceptance['withdrawalDeadline'] in body
        for line in data['withdrawalFormText'].splitlines():
            assert normalized(line) in body, 'Incomplete withdrawal form'
    else:
        assert 'Ångerblankett' not in '\n'.join(pages)
    with pdfplumber.open(case['pdf']) as pdf:
        for number, page in enumerate(pdf.pages, 1):
            assert f'{number} ({len(pages)})' in page.extract_text(), 'Missing page number'
            for char in page.chars:
                if char['text'].isspace():
                    continue  # Layout may retain a trailing space just outside a line box.
                assert 38 <= char['x0'] <= char['x1'] <= page.width - 38, 'Text outside horizontal margins'
                assert 24 <= char['top'] < char['bottom'] <= 822, 'Text outside vertical margins'
            assert all(char['bottom'] < 791 for char in page.chars if char['top'] < 797), 'Content collides with footer'
    print(f'PASS: {len(pages)} pages, full agreement/consents/facts, margins and page numbers: {Path(case["pdf"]).name}')
